RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "The Trainers' School is excellent.\pIf you study there, you might one\nday become a Gym Leader.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "The Gym Leader, Roxanne, knows a lot\nabout Pokémon.\pShe's really strong, too!$"

