
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                              0
#define PARTNER_MAY_METEOR_FALLS_TREECKO          1
#define PARTNER_MAY_METEOR_FALLS_TORCHIC          2
#define PARTNER_MAY_METEOR_FALLS_MUDKIP           3
#define PARTNER_BRENDAN_METEOR_FALLS_TREECKO      4
#define PARTNER_BRENDAN_METEOR_FALLS_TORCHIC      5
#define PARTNER_BRENDAN_METEOR_FALLS_MUDKIP       6
#define PARTNER_STEVEN_SOUTHERN_ISLAND            7
#define PARTNER_STEVEN_MOSSDEEP_SPACE_CENTER      8
#define PARTNER_COUNT 9

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
