#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#include "constants/global.h"
#include "constants/map_event_ids.h"

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238

#define OBJ_EVENT_GFX_POKE_BALL                  239
#define OBJ_EVENT_GFX_OW_MON                     240
#define OBJ_EVENT_GFX_LIGHT_SPRITE               241

#define OBJ_EVENT_GFX_DELTA_BRENDAN_ACRO_BIKE    (OBJ_EVENT_GFX_LIGHT_SPRITE + 1)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_DECORATING   (OBJ_EVENT_GFX_LIGHT_SPRITE + 2)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_FIELD_MOVE   (OBJ_EVENT_GFX_LIGHT_SPRITE + 3)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_FISHING      (OBJ_EVENT_GFX_LIGHT_SPRITE + 4)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_MACH_BIKE    (OBJ_EVENT_GFX_LIGHT_SPRITE + 5)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_SURFING      (OBJ_EVENT_GFX_LIGHT_SPRITE + 6)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_UNDERWATER   (OBJ_EVENT_GFX_LIGHT_SPRITE + 7)
#define OBJ_EVENT_GFX_DELTA_BRENDAN              (OBJ_EVENT_GFX_LIGHT_SPRITE + 8)
#define OBJ_EVENT_GFX_DELTA_BRENDAN_WATERING     (OBJ_EVENT_GFX_LIGHT_SPRITE + 9)
#define OBJ_EVENT_GFX_DELTA_MAY_ACRO_BIKE        (OBJ_EVENT_GFX_LIGHT_SPRITE + 10)
#define OBJ_EVENT_GFX_DELTA_MAY_DECORATING       (OBJ_EVENT_GFX_LIGHT_SPRITE + 11)
#define OBJ_EVENT_GFX_DELTA_MAY_FIELD_MOVE       (OBJ_EVENT_GFX_LIGHT_SPRITE + 12)
#define OBJ_EVENT_GFX_DELTA_MAY_FISHING          (OBJ_EVENT_GFX_LIGHT_SPRITE + 13)
#define OBJ_EVENT_GFX_DELTA_MAY_MACH_BIKE        (OBJ_EVENT_GFX_LIGHT_SPRITE + 14)
#define OBJ_EVENT_GFX_DELTA_MAY_SURFING          (OBJ_EVENT_GFX_LIGHT_SPRITE + 15)
#define OBJ_EVENT_GFX_DELTA_MAY_UNDERWATER       (OBJ_EVENT_GFX_LIGHT_SPRITE + 16)
#define OBJ_EVENT_GFX_DELTA_MAY                  (OBJ_EVENT_GFX_LIGHT_SPRITE + 17)
#define OBJ_EVENT_GFX_DELTA_MAY_WATERING         (OBJ_EVENT_GFX_LIGHT_SPRITE + 18)

#define OBJ_EVENT_GFX_AQUA_MATT                  (OBJ_EVENT_GFX_LIGHT_SPRITE + 19)
#define OBJ_EVENT_GFX_AQUA_SHELLY                (OBJ_EVENT_GFX_LIGHT_SPRITE + 20)
#define OBJ_EVENT_GFX_MAGMA_COURTNEY             (OBJ_EVENT_GFX_LIGHT_SPRITE + 21)
#define OBJ_EVENT_GFX_MAGMA_TABITHA              (OBJ_EVENT_GFX_LIGHT_SPRITE + 22)

#define OBJ_EVENT_GFX_GOLD_ITEM_BALL             (OBJ_EVENT_GFX_LIGHT_SPRITE + 23)
#define OBJ_EVENT_GFX_MEGA_STONE                 (OBJ_EVENT_GFX_LIGHT_SPRITE + 24)

#define OBJ_EVENT_GFX_AROMA_LADY_FRLG            (OBJ_EVENT_GFX_LIGHT_SPRITE + 25)
#define OBJ_EVENT_GFX_BATTLE_GIRL_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 26)
#define OBJ_EVENT_GFX_BEAUTY_2_RSE               (OBJ_EVENT_GFX_LIGHT_SPRITE + 27)
#define OBJ_EVENT_GFX_BIRD_KEEPER_FRLG           (OBJ_EVENT_GFX_LIGHT_SPRITE + 28)
#define OBJ_EVENT_GFX_BLACK_BELT_2_FRLG          (OBJ_EVENT_GFX_LIGHT_SPRITE + 29)
#define OBJ_EVENT_GFX_BUG_MANIAC_RSE             (OBJ_EVENT_GFX_LIGHT_SPRITE + 30)
#define OBJ_EVENT_GFX_CAMPER_2_RSE               (OBJ_EVENT_GFX_LIGHT_SPRITE + 31)
#define OBJ_EVENT_GFX_COLLECTOR_RSE              (OBJ_EVENT_GFX_LIGHT_SPRITE + 32)
#define OBJ_EVENT_GFX_COOLTRAINER_TRAINER_F_RSE  (OBJ_EVENT_GFX_LIGHT_SPRITE + 33)
#define OBJ_EVENT_GFX_COOLTRAINER_TRAINER_M_RSE  (OBJ_EVENT_GFX_LIGHT_SPRITE + 34)
#define OBJ_EVENT_GFX_DRAGON_TAMER_RSE           (OBJ_EVENT_GFX_LIGHT_SPRITE + 35)
#define OBJ_EVENT_GFX_EXPERT_F_2_RSE             (OBJ_EVENT_GFX_LIGHT_SPRITE + 36)
#define OBJ_EVENT_GFX_EXPERT_M_2_RSE             (OBJ_EVENT_GFX_LIGHT_SPRITE + 37)
#define OBJ_EVENT_GFX_FISHERMAN_2_FRLG           (OBJ_EVENT_GFX_LIGHT_SPRITE + 38)
#define OBJ_EVENT_GFX_GENTLEMAN_2_FRLG           (OBJ_EVENT_GFX_LIGHT_SPRITE + 39)
#define OBJ_EVENT_GFX_GUITARIST_RSE              (OBJ_EVENT_GFX_LIGHT_SPRITE + 40)
#define OBJ_EVENT_GFX_HEX_MANIAC_2_ORAS          (OBJ_EVENT_GFX_LIGHT_SPRITE + 41)
#define OBJ_EVENT_GFX_HIKER_2_RSE                (OBJ_EVENT_GFX_LIGHT_SPRITE + 42)
#define OBJ_EVENT_GFX_KINDLER_RSE                (OBJ_EVENT_GFX_LIGHT_SPRITE + 43)
#define OBJ_EVENT_GFX_LADY_FRLG                  (OBJ_EVENT_GFX_LIGHT_SPRITE + 44)
#define OBJ_EVENT_GFX_LASS_2_RSE                 (OBJ_EVENT_GFX_LIGHT_SPRITE + 45)
#define OBJ_EVENT_GFX_NINJA_BOY_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 46)
#define OBJ_EVENT_GFX_PARASOL_LADY_RSE           (OBJ_EVENT_GFX_LIGHT_SPRITE + 47)
#define OBJ_EVENT_GFX_PICNICKER_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 48)
#define OBJ_EVENT_GFX_POKEFAN_F_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 49)
#define OBJ_EVENT_GFX_POKEFAN_M_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 50)
#define OBJ_EVENT_GFX_POKEMANIAC_FRLG            (OBJ_EVENT_GFX_LIGHT_SPRITE + 51)
#define OBJ_EVENT_GFX_POKEMON_BREEDER_F_RSE      (OBJ_EVENT_GFX_LIGHT_SPRITE + 52)
#define OBJ_EVENT_GFX_POKEMON_BREEDER_M_RSE      (OBJ_EVENT_GFX_LIGHT_SPRITE + 53)
#define OBJ_EVENT_GFX_POKEMON_RANGER_F_RSE       (OBJ_EVENT_GFX_LIGHT_SPRITE + 54)
#define OBJ_EVENT_GFX_POKEMON_RANGER_M_RSE       (OBJ_EVENT_GFX_LIGHT_SPRITE + 55)
#define OBJ_EVENT_GFX_PSYCHIC_F_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 56)
#define OBJ_EVENT_GFX_PSYCHIC_M_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 57)
#define OBJ_EVENT_GFX_RICH_BOY_2_FRLG            (OBJ_EVENT_GFX_LIGHT_SPRITE + 58)
#define OBJ_EVENT_GFX_RUIN_MANIAC_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 59)
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F_2_RSE (OBJ_EVENT_GFX_LIGHT_SPRITE + 60)
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M_2_RSE (OBJ_EVENT_GFX_LIGHT_SPRITE + 61)
#define OBJ_EVENT_GFX_SAILOR_2_FRLG              (OBJ_EVENT_GFX_LIGHT_SPRITE + 62)
#define OBJ_EVENT_GFX_SCHOOL_KID_F_RSE           (OBJ_EVENT_GFX_LIGHT_SPRITE + 63)
#define OBJ_EVENT_GFX_SWIMMER_F_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 64)
#define OBJ_EVENT_GFX_SWIMMER_M_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 65)
#define OBJ_EVENT_GFX_TWIN_2_RSE                 (OBJ_EVENT_GFX_LIGHT_SPRITE + 66)
#define OBJ_EVENT_GFX_YOUNG_COUPLE_F_FRLG        (OBJ_EVENT_GFX_LIGHT_SPRITE + 67)
#define OBJ_EVENT_GFX_YOUNG_COUPLE_M_FRLG        (OBJ_EVENT_GFX_LIGHT_SPRITE + 68)
#define OBJ_EVENT_GFX_YOUNGSTER_2_RSE            (OBJ_EVENT_GFX_LIGHT_SPRITE + 69)

// NOTE: The maximum amount of object events has been expanded from 255 to 65535.
// Since dynamic graphics ids still require at least 16 free values, the actual limit
// is 65519, but even considering follower Pokémon, this should be more than enough :)
#define NUM_OBJ_EVENT_GFX                        OBJ_EVENT_GFX_YOUNGSTER_2_RSE + 1


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF)

// Don't use (1u << 15) to avoid conflict with BLEND_IMMUNE_FLAG.
#define OBJ_EVENT_MON               (1u << 14)
#define OBJ_EVENT_MON_SHINY         (1u << 13)
#define OBJ_EVENT_MON_FEMALE        (1u << 12)
#define OBJ_EVENT_MON_SPECIES_MASK  (~(7u << 12))

// Used to call a specific species' follower graphics. Useful for static encounters.
#define OBJ_EVENT_GFX_SPECIES(name)                 (SPECIES_##name + OBJ_EVENT_MON)
#define OBJ_EVENT_GFX_SPECIES_SHINY(name)           (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_SHINY)
#define OBJ_EVENT_GFX_SPECIES_FEMALE(name)          (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_FEMALE)
#define OBJ_EVENT_GFX_SPECIES_SHINY_FEMALE(name)    (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_SHINY + OBJ_EVENT_MON_FEMALE)

#define OW_SPECIES(x) ((x)->graphicsId & OBJ_EVENT_MON_SPECIES_MASK)
#define OW_SHINY(x) ((x)->graphicsId & OBJ_EVENT_MON_SHINY)
#define OW_FEMALE(x) ((x)->graphicsId & OBJ_EVENT_MON_FEMALE)

// Whether Object Event is an OW pokemon
#define IS_OW_MON_OBJ(obj) ((obj)->graphicsId & OBJ_EVENT_MON)

#define SHADOW_SIZE_S       0
#define SHADOW_SIZE_M       1
#define SHADOW_SIZE_L       2
#define SHADOW_SIZE_NONE    3   // Originally SHADOW_SIZE_XL, which went unused due to shadowSize in ObjectEventGraphicsInfo being only 2 bits.

#define SHADOW_SIZE_XL_BATTLE_ONLY  SHADOW_SIZE_NONE    // Battle-only definition for XL shadow size.

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define LIGHT_TYPE_BALL             0
#define LIGHT_TYPE_PKMN_CENTER_SIGN 1
#define LIGHT_TYPE_POKE_MART_SIGN   2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_DYNAMIC_BASE 0xF0

// Each object event template gets an ID that can be used to refer to it in scripts and elsewhere.
// This is referred to as the "local id" (and it's really just 1 + its index in the templates array).
// There are a few special IDs reserved for objects that don't have templates in the map data -- one for the player
// in regular offline play, five for linked players while playing Berry Blender, and one for an invisible object that
// can be spawned for the camera to track instead of the player. Additionally, the value 0 is reserved as an "empty" indicator.
#define LOCALID_NONE                         0
#define LOCALID_CAMERA                     127
#define LOCALID_BERRY_BLENDER_PLAYER_END   240 // This will use 5 (MAX_RFU_PLAYERS) IDs ending at 240, i.e. 236-240
#define LOCALID_FOLLOWING_POKEMON          254
#define LOCALID_PLAYER                     255
#define OBJ_EVENT_ID_FOLLOWER              0xFE
#define OBJ_EVENT_ID_NPC_FOLLOWER          0xFD

// Aliases for old names. "object event id" normally refers to an index into gObjectEvents, which these are not.
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_DYNAMIC_BASE 0xF0
#define OBJ_EVENT_ID_CAMERA LOCALID_CAMERA
#define OBJ_EVENT_ID_PLAYER LOCALID_PLAYER

// Moved from src/event_object_movement.c so that they're accesible from other files.
#define OBJ_EVENT_PAL_TAG_BRENDAN                 0x1100
#define OBJ_EVENT_PAL_TAG_BRENDAN_REFLECTION      0x1101
#define OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION       0x1102
#define OBJ_EVENT_PAL_TAG_NPC_1                   0x1103
#define OBJ_EVENT_PAL_TAG_NPC_2                   0x1104
#define OBJ_EVENT_PAL_TAG_NPC_3                   0x1105
#define OBJ_EVENT_PAL_TAG_NPC_4                   0x1106
#define OBJ_EVENT_PAL_TAG_NPC_1_REFLECTION        0x1107
#define OBJ_EVENT_PAL_TAG_NPC_2_REFLECTION        0x1108
#define OBJ_EVENT_PAL_TAG_NPC_3_REFLECTION        0x1109
#define OBJ_EVENT_PAL_TAG_NPC_4_REFLECTION        0x110A
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP            0x110B
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP_REFLECTION 0x110C
#define OBJ_EVENT_PAL_TAG_TRUCK                   0x110D
#define OBJ_EVENT_PAL_TAG_VIGOROTH                0x110E
#define OBJ_EVENT_PAL_TAG_ZIGZAGOON               0x110F
#define OBJ_EVENT_PAL_TAG_MAY                     0x1110
#define OBJ_EVENT_PAL_TAG_MAY_REFLECTION          0x1111
#define OBJ_EVENT_PAL_TAG_MOVING_BOX              0x1112
#define OBJ_EVENT_PAL_TAG_CABLE_CAR               0x1113
#define OBJ_EVENT_PAL_TAG_SSTIDAL                 0x1114
#define OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER       0x1115
#define OBJ_EVENT_PAL_TAG_KYOGRE                  0x1116
#define OBJ_EVENT_PAL_TAG_KYOGRE_REFLECTION       0x1117
#define OBJ_EVENT_PAL_TAG_GROUDON                 0x1118
#define OBJ_EVENT_PAL_TAG_GROUDON_REFLECTION      0x1119
#define OBJ_EVENT_PAL_TAG_UNUSED                  0x111A
#define OBJ_EVENT_PAL_TAG_SUBMARINE_SHADOW        0x111B
#define OBJ_EVENT_PAL_TAG_POOCHYENA               0x111C
#define OBJ_EVENT_PAL_TAG_RED_LEAF                0x111D
#define OBJ_EVENT_PAL_TAG_DEOXYS                  0x111E
#define OBJ_EVENT_PAL_TAG_BIRTH_ISLAND_STONE      0x111F
#define OBJ_EVENT_PAL_TAG_HO_OH                   0x1120
#define OBJ_EVENT_PAL_TAG_LUGIA                   0x1121
#define OBJ_EVENT_PAL_TAG_RS_BRENDAN              0x1122
#define OBJ_EVENT_PAL_TAG_RS_MAY                  0x1123
#define OBJ_EVENT_PAL_TAG_DYNAMIC                 0x1124

// Start of my added palettes
#define OBJ_EVENT_PAL_TAG_EXPANSION_END              OBJ_EVENT_PAL_TAG_DYNAMIC

#define OBJ_EVENT_PAL_TAG_DELTA_BRENDAN              OBJ_EVENT_PAL_TAG_EXPANSION_END + 1
#define OBJ_EVENT_PAL_TAG_DELTA_BRENDAN_UNDERWATER   OBJ_EVENT_PAL_TAG_EXPANSION_END + 2
#define OBJ_EVENT_PAL_TAG_DELTA_MAY                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 3
#define OBJ_EVENT_PAL_TAG_DELTA_MAY_UNDERWATER       OBJ_EVENT_PAL_TAG_EXPANSION_END + 4

#define OBJ_EVENT_PAL_TAG_ARTIST                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 5
#define OBJ_EVENT_PAL_TAG_BEAUTY                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 6
#define OBJ_EVENT_PAL_TAG_BLACK_BELT                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 7
#define OBJ_EVENT_PAL_TAG_BOY_1                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 8
#define OBJ_EVENT_PAL_TAG_BOY_2                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 9
#define OBJ_EVENT_PAL_TAG_BOY_3                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 10
#define OBJ_EVENT_PAL_TAG_BUG_CATCHER                OBJ_EVENT_PAL_TAG_EXPANSION_END + 11
#define OBJ_EVENT_PAL_TAG_CAMERA_MAN                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 12
#define OBJ_EVENT_PAL_TAG_CAMPER                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 13
#define OBJ_EVENT_PAL_TAG_CONTEST_JUDGE              OBJ_EVENT_PAL_TAG_EXPANSION_END + 14
#define OBJ_EVENT_PAL_TAG_COOK                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 15
#define OBJ_EVENT_PAL_TAG_CYCLING_TRAINER_F          OBJ_EVENT_PAL_TAG_EXPANSION_END + 16
#define OBJ_EVENT_PAL_TAG_CYCLING_TRAINER_M          OBJ_EVENT_PAL_TAG_EXPANSION_END + 17   
#define OBJ_EVENT_PAL_TAG_DEVON_EMPLOYEE             OBJ_EVENT_PAL_TAG_EXPANSION_END + 18
#define OBJ_EVENT_PAL_TAG_EXPERT_F                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 19
#define OBJ_EVENT_PAL_TAG_EXPERT_M                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 20
#define OBJ_EVENT_PAL_TAG_FAT_MAN                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 21
#define OBJ_EVENT_PAL_TAG_FISHER_MAN                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 22
#define OBJ_EVENT_PAL_TAG_GAMEBOY_KID                OBJ_EVENT_PAL_TAG_EXPANSION_END + 23
#define OBJ_EVENT_PAL_TAG_GENTLEMAN                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 24
#define OBJ_EVENT_PAL_TAG_GIRL_1                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 25
#define OBJ_EVENT_PAL_TAG_GIRL_2                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 26
#define OBJ_EVENT_PAL_TAG_GIRL_3                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 27
#define OBJ_EVENT_PAL_TAG_HEX_MANIAC                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 28
#define OBJ_EVENT_PAL_TAG_HIKER                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 29
#define OBJ_EVENT_PAL_TAG_HOT_SPRINGS_OLD_WOMAN      OBJ_EVENT_PAL_TAG_EXPANSION_END + 30
#define OBJ_EVENT_PAL_TAG_LASS                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 31
#define OBJ_EVENT_PAL_TAG_LEAF                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 32
#define OBJ_EVENT_PAL_TAG_LINK_RECEPTIONIST          OBJ_EVENT_PAL_TAG_EXPANSION_END + 33
#define OBJ_EVENT_PAL_TAG_LITTLE_BOY                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 34
#define OBJ_EVENT_PAL_TAG_LITTLE_GIRL                OBJ_EVENT_PAL_TAG_EXPANSION_END + 35
#define OBJ_EVENT_PAL_TAG_MAN_1                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 36
#define OBJ_EVENT_PAL_TAG_MAN_2                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 37
#define OBJ_EVENT_PAL_TAG_MAN_3                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 38
#define OBJ_EVENT_PAL_TAG_MAN_4                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 39
#define OBJ_EVENT_PAL_TAG_MAN_5                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 40
#define OBJ_EVENT_PAL_TAG_MANIAC                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 41
#define OBJ_EVENT_PAL_TAG_MART_EMPLOYEE              OBJ_EVENT_PAL_TAG_EXPANSION_END + 42
#define OBJ_EVENT_PAL_TAG_MAUVILLE_OLD_MAN_1         OBJ_EVENT_PAL_TAG_EXPANSION_END + 43
#define OBJ_EVENT_PAL_TAG_MAUVILLE_OLD_MAN_2         OBJ_EVENT_PAL_TAG_EXPANSION_END + 44
#define OBJ_EVENT_PAL_TAG_MOM                        OBJ_EVENT_PAL_TAG_EXPANSION_END + 45
#define OBJ_EVENT_PAL_TAG_MYSTERY_EVENT_DELIVERY_MAN OBJ_EVENT_PAL_TAG_EXPANSION_END + 46
#define OBJ_EVENT_PAL_TAG_NINJA_BOY                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 47
#define OBJ_EVENT_PAL_TAG_NURSE                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 48
#define OBJ_EVENT_PAL_TAG_OLD_MAN                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 49
#define OBJ_EVENT_PAL_TAG_OLD_WOMAN                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 50
#define OBJ_EVENT_PAL_TAG_PIC_NICKER                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 51
#define OBJ_EVENT_PAL_TAG_POKEFAN_F                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 52
#define OBJ_EVENT_PAL_TAG_POKEFAN_M                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 53
#define OBJ_EVENT_PAL_TAG_PROF_BIRCH                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 54
#define OBJ_EVENT_PAL_TAG_PSYCHIC_M                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 55
#define OBJ_EVENT_PAL_TAG_RED                        OBJ_EVENT_PAL_TAG_EXPANSION_END + 56
#define OBJ_EVENT_PAL_TAG_REPORTER_F                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 57
#define OBJ_EVENT_PAL_TAG_REPORTER_M                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 58
#define OBJ_EVENT_PAL_TAG_RICH_BOY                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 59
#define OBJ_EVENT_PAL_TAG_ROOFTOP_SALE_WOMAN         OBJ_EVENT_PAL_TAG_EXPANSION_END + 60
#define OBJ_EVENT_PAL_TAG_RS_LITTLE_BOY              OBJ_EVENT_PAL_TAG_EXPANSION_END + 61
#define OBJ_EVENT_PAL_TAG_RUNNING_TRIATHLETE_F       OBJ_EVENT_PAL_TAG_EXPANSION_END + 62
#define OBJ_EVENT_PAL_TAG_RUNNING_TRIATHLETE_M       OBJ_EVENT_PAL_TAG_EXPANSION_END + 63
#define OBJ_EVENT_PAL_TAG_SAILOR                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 64
#define OBJ_EVENT_PAL_TAG_SCHOOL_KID_M               OBJ_EVENT_PAL_TAG_EXPANSION_END + 65
#define OBJ_EVENT_PAL_TAG_SCIENTIST_1                OBJ_EVENT_PAL_TAG_EXPANSION_END + 66
#define OBJ_EVENT_PAL_TAG_SCIENTIST_2                OBJ_EVENT_PAL_TAG_EXPANSION_END + 67
#define OBJ_EVENT_PAL_TAG_SCOTT                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 68
#define OBJ_EVENT_PAL_TAG_STEVEN                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 69
#define OBJ_EVENT_PAL_TAG_SWIMMER_F                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 70
#define OBJ_EVENT_PAL_TAG_SWIMMER_M                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 71
#define OBJ_EVENT_PAL_TAG_TEALA                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 72
#define OBJ_EVENT_PAL_TAG_TUBER_F                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 73
#define OBJ_EVENT_PAL_TAG_TUBER_M                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 74
#define OBJ_EVENT_PAL_TAG_TUBER_M_SWIMMING           OBJ_EVENT_PAL_TAG_EXPANSION_END + 75
#define OBJ_EVENT_PAL_TAG_TWIN                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 76
#define OBJ_EVENT_PAL_TAG_UNION_ROOM_ATTENDANT       OBJ_EVENT_PAL_TAG_EXPANSION_END + 77
#define OBJ_EVENT_PAL_TAG_UNUSED_WOMAN               OBJ_EVENT_PAL_TAG_EXPANSION_END + 78
#define OBJ_EVENT_PAL_TAG_WALLACE                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 79
#define OBJ_EVENT_PAL_TAG_WALLY                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 80
#define OBJ_EVENT_PAL_TAG_WOMAN_1                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 81
#define OBJ_EVENT_PAL_TAG_WOMAN_2                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 82
#define OBJ_EVENT_PAL_TAG_WOMAN_3                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 83
#define OBJ_EVENT_PAL_TAG_WOMAN_4                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 84
#define OBJ_EVENT_PAL_TAG_WOMAN_5                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 85
#define OBJ_EVENT_PAL_TAG_YOUNGSTER                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 86

#define OBJ_EVENT_PAL_TAG_DRAKE                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 87
#define OBJ_EVENT_PAL_TAG_GLACIA                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 88
#define OBJ_EVENT_PAL_TAG_PHOEBE                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 89
#define OBJ_EVENT_PAL_TAG_SIDNEY                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 90

#define OBJ_EVENT_PAL_TAG_ANABEL                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 91
#define OBJ_EVENT_PAL_TAG_BRANDON                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 92
#define OBJ_EVENT_PAL_TAG_GRETA                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 93
#define OBJ_EVENT_PAL_TAG_LUCY                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 94
#define OBJ_EVENT_PAL_TAG_NOLAND                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 95
#define OBJ_EVENT_PAL_TAG_SPENSER                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 96
#define OBJ_EVENT_PAL_TAG_TUCKER                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 97

#define OBJ_EVENT_PAL_TAG_BRAWLY                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 98
#define OBJ_EVENT_PAL_TAG_FLANNERY                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 99
#define OBJ_EVENT_PAL_TAG_JUAN                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 100
#define OBJ_EVENT_PAL_TAG_LIZA                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 101
#define OBJ_EVENT_PAL_TAG_NORMAN                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 102
#define OBJ_EVENT_PAL_TAG_ROXANNE                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 103
#define OBJ_EVENT_PAL_TAG_TATE                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 104
#define OBJ_EVENT_PAL_TAG_WATTSON                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 105
#define OBJ_EVENT_PAL_TAG_WINONA                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 106

#define OBJ_EVENT_PAL_TAG_AQUA_MEMBER_F              OBJ_EVENT_PAL_TAG_EXPANSION_END + 107
#define OBJ_EVENT_PAL_TAG_AQUA_MEMBER_M              OBJ_EVENT_PAL_TAG_EXPANSION_END + 108
#define OBJ_EVENT_PAL_TAG_ARCHIE                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 109

#define OBJ_EVENT_PAL_TAG_MAGMA_MEMBER_F             OBJ_EVENT_PAL_TAG_EXPANSION_END + 110
#define OBJ_EVENT_PAL_TAG_MAGMA_MEMBER_M             OBJ_EVENT_PAL_TAG_EXPANSION_END + 111
#define OBJ_EVENT_PAL_TAG_MAXIE                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 112

#define OBJ_EVENT_PAL_TAG_MATT                       OBJ_EVENT_PAL_TAG_EXPANSION_END + 113
#define OBJ_EVENT_PAL_TAG_SHELLY                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 114
#define OBJ_EVENT_PAL_TAG_COURTNEY                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 115
#define OBJ_EVENT_PAL_TAG_TABITHA                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 116
#define OBJ_EVENT_PAL_TAG_LATIAS                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 117
#define OBJ_EVENT_PAL_TAG_LATIOS                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 118

#define OBJ_EVENT_PAL_TAG_AROMA_LADY_FRLG                OBJ_EVENT_PAL_TAG_EXPANSION_END + 119
#define OBJ_EVENT_PAL_TAG_BATTLE_GIRL_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 120
#define OBJ_EVENT_PAL_TAG_BEAUTY_2_RSE                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 121
#define OBJ_EVENT_PAL_TAG_BIRD_KEEPER_FRLG               OBJ_EVENT_PAL_TAG_EXPANSION_END + 122
#define OBJ_EVENT_PAL_TAG_BLACK_BELT_2_FRLG              OBJ_EVENT_PAL_TAG_EXPANSION_END + 123
#define OBJ_EVENT_PAL_TAG_BUG_MANIAC_RSE                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 124
#define OBJ_EVENT_PAL_TAG_CAMPER_2_RSE                   OBJ_EVENT_PAL_TAG_EXPANSION_END + 125
#define OBJ_EVENT_PAL_TAG_COLLECTOR_RSE                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 126
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_TRAINER_M_RSE      OBJ_EVENT_PAL_TAG_EXPANSION_END + 127
#define OBJ_EVENT_PAL_TAG_COOLTRAINER_TRAINER_F_RSE      OBJ_EVENT_PAL_TAG_EXPANSION_END + 128
#define OBJ_EVENT_PAL_TAG_DRAGON_TAMER_RSE               OBJ_EVENT_PAL_TAG_EXPANSION_END + 129
#define OBJ_EVENT_PAL_TAG_EXPERT_F_2_RSE                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 130
#define OBJ_EVENT_PAL_TAG_EXPERT_M_2_RSE                 OBJ_EVENT_PAL_TAG_EXPANSION_END + 131
#define OBJ_EVENT_PAL_TAG_FISHERMAN_2_FRLG               OBJ_EVENT_PAL_TAG_EXPANSION_END + 132
#define OBJ_EVENT_PAL_TAG_GENTLEMAN_2_FRLG               OBJ_EVENT_PAL_TAG_EXPANSION_END + 133
#define OBJ_EVENT_PAL_TAG_GUITARIST_RSE                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 134
#define OBJ_EVENT_PAL_TAG_HEX_MANIAC_2_ORAS              OBJ_EVENT_PAL_TAG_EXPANSION_END + 135
#define OBJ_EVENT_PAL_TAG_HIKER_2_RSE                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 136
#define OBJ_EVENT_PAL_TAG_KINDLER_RSE                    OBJ_EVENT_PAL_TAG_EXPANSION_END + 137
#define OBJ_EVENT_PAL_TAG_LADY_FRLG                      OBJ_EVENT_PAL_TAG_EXPANSION_END + 138
#define OBJ_EVENT_PAL_TAG_LASS_2_RSE                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 139
#define OBJ_EVENT_PAL_TAG_NINJA_BOY_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 140
#define OBJ_EVENT_PAL_TAG_PARASOL_LADY_RSE               OBJ_EVENT_PAL_TAG_EXPANSION_END + 141
#define OBJ_EVENT_PAL_TAG_PICNICKER_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 142
#define OBJ_EVENT_PAL_TAG_POKEFAN_F_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 143
#define OBJ_EVENT_PAL_TAG_POKEFAN_M_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 144
#define OBJ_EVENT_PAL_TAG_POKEMANIAC_FRLG                OBJ_EVENT_PAL_TAG_EXPANSION_END + 145
#define OBJ_EVENT_PAL_TAG_POKEMON_BREEDER_F_RSE          OBJ_EVENT_PAL_TAG_EXPANSION_END + 146
#define OBJ_EVENT_PAL_TAG_POKEMON_BREEDER_M_RSE          OBJ_EVENT_PAL_TAG_EXPANSION_END + 147
#define OBJ_EVENT_PAL_TAG_POKEMON_RANGER_F_RSE           OBJ_EVENT_PAL_TAG_EXPANSION_END + 148
#define OBJ_EVENT_PAL_TAG_POKEMON_RANGER_M_RSE           OBJ_EVENT_PAL_TAG_EXPANSION_END + 149
#define OBJ_EVENT_PAL_TAG_PSYCHIC_F_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 150
#define OBJ_EVENT_PAL_TAG_PSYCHIC_M_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 151
#define OBJ_EVENT_PAL_TAG_RICH_BOY_2_FRLG                OBJ_EVENT_PAL_TAG_EXPANSION_END + 152
#define OBJ_EVENT_PAL_TAG_RUIN_MANIAC_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 153
#define OBJ_EVENT_PAL_TAG_RUNNING_TRIATHLETE_F_2_RSE     OBJ_EVENT_PAL_TAG_EXPANSION_END + 154
#define OBJ_EVENT_PAL_TAG_RUNNING_TRIATHLETE_M_2_RSE     OBJ_EVENT_PAL_TAG_EXPANSION_END + 155
#define OBJ_EVENT_PAL_TAG_SAILOR_2_FRLG                  OBJ_EVENT_PAL_TAG_EXPANSION_END + 156
#define OBJ_EVENT_PAL_TAG_SCHOOL_KID_F_RSE               OBJ_EVENT_PAL_TAG_EXPANSION_END + 157
#define OBJ_EVENT_PAL_TAG_SWIMMER_F_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 158
#define OBJ_EVENT_PAL_TAG_SWIMMER_M_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 159
#define OBJ_EVENT_PAL_TAG_TWIN_2_RSE                     OBJ_EVENT_PAL_TAG_EXPANSION_END + 160
#define OBJ_EVENT_PAL_TAG_YOUNG_COUPLE_F_FRLG            OBJ_EVENT_PAL_TAG_EXPANSION_END + 161
#define OBJ_EVENT_PAL_TAG_YOUNG_COUPLE_M_FRLG            OBJ_EVENT_PAL_TAG_EXPANSION_END + 162
#define OBJ_EVENT_PAL_TAG_YOUNGSTER_2_RSE                OBJ_EVENT_PAL_TAG_EXPANSION_END + 163

// ^ Above Custom End
#define OBJ_EVENT_PAL_TAG_ADDED                      OBJ_EVENT_GFX_YOUNGSTER_2_RSE

#if OW_FOLLOWERS_POKEBALLS
// Vanilla
#define OBJ_EVENT_PAL_TAG_BALL_MASTER             OBJ_EVENT_PAL_TAG_ADDED + 1
#define OBJ_EVENT_PAL_TAG_BALL_ULTRA              OBJ_EVENT_PAL_TAG_ADDED + 2
#define OBJ_EVENT_PAL_TAG_BALL_GREAT              OBJ_EVENT_PAL_TAG_ADDED + 3
#define OBJ_EVENT_PAL_TAG_BALL_SAFARI             OBJ_EVENT_PAL_TAG_ADDED + 4
#define OBJ_EVENT_PAL_TAG_BALL_NET                OBJ_EVENT_PAL_TAG_ADDED + 5
#define OBJ_EVENT_PAL_TAG_BALL_DIVE               OBJ_EVENT_PAL_TAG_ADDED + 6
#define OBJ_EVENT_PAL_TAG_BALL_NEST               OBJ_EVENT_PAL_TAG_ADDED + 7
#define OBJ_EVENT_PAL_TAG_BALL_REPEAT             OBJ_EVENT_PAL_TAG_ADDED + 8
#define OBJ_EVENT_PAL_TAG_BALL_TIMER              OBJ_EVENT_PAL_TAG_ADDED + 9
#define OBJ_EVENT_PAL_TAG_BALL_LUXURY             OBJ_EVENT_PAL_TAG_ADDED + 10
#define OBJ_EVENT_PAL_TAG_BALL_PREMIER            OBJ_EVENT_PAL_TAG_ADDED + 11
// Gen IV/Sinnoh
#define OBJ_EVENT_PAL_TAG_BALL_DUSK               OBJ_EVENT_PAL_TAG_ADDED + 12
#define OBJ_EVENT_PAL_TAG_BALL_HEAL               OBJ_EVENT_PAL_TAG_ADDED + 13
#define OBJ_EVENT_PAL_TAG_BALL_QUICK              OBJ_EVENT_PAL_TAG_ADDED + 14
#define OBJ_EVENT_PAL_TAG_BALL_CHERISH            OBJ_EVENT_PAL_TAG_ADDED + 15
#define OBJ_EVENT_PAL_TAG_BALL_PARK               OBJ_EVENT_PAL_TAG_ADDED + 16
// Gen II/Johto Apricorns
#define OBJ_EVENT_PAL_TAG_BALL_FAST               OBJ_EVENT_PAL_TAG_ADDED + 17
#define OBJ_EVENT_PAL_TAG_BALL_LEVEL              OBJ_EVENT_PAL_TAG_ADDED + 18
#define OBJ_EVENT_PAL_TAG_BALL_LURE               OBJ_EVENT_PAL_TAG_ADDED + 19
#define OBJ_EVENT_PAL_TAG_BALL_HEAVY              OBJ_EVENT_PAL_TAG_ADDED + 20
#define OBJ_EVENT_PAL_TAG_BALL_LOVE               OBJ_EVENT_PAL_TAG_ADDED + 21
#define OBJ_EVENT_PAL_TAG_BALL_FRIEND             OBJ_EVENT_PAL_TAG_ADDED + 22
#define OBJ_EVENT_PAL_TAG_BALL_MOON               OBJ_EVENT_PAL_TAG_ADDED + 23
#define OBJ_EVENT_PAL_TAG_BALL_SPORT              OBJ_EVENT_PAL_TAG_ADDED + 24
// Gen V
#define OBJ_EVENT_PAL_TAG_BALL_DREAM              OBJ_EVENT_PAL_TAG_ADDED + 25
// Gen VII
#define OBJ_EVENT_PAL_TAG_BALL_BEAST              OBJ_EVENT_PAL_TAG_ADDED + 26
// Gen VIII
#define OBJ_EVENT_PAL_TAG_BALL_STRANGE            OBJ_EVENT_PAL_TAG_ADDED + 27
#endif //OW_FOLLOWERS_POKEBALLS
// Used as a placeholder follower graphic
#define OBJ_EVENT_PAL_TAG_SUBSTITUTE              0x7611
#define OBJ_EVENT_PAL_TAG_LIGHT                   0x8001
#define OBJ_EVENT_PAL_TAG_LIGHT_2                 0x8002
#define OBJ_EVENT_PAL_TAG_EMOTES                  0x8003
#define OBJ_EVENT_PAL_TAG_NEON_LIGHT              0x8004
// Not a real OW palette tag; used for the white flash applied to followers
#define OBJ_EVENT_PAL_TAG_WHITE                   (OBJ_EVENT_PAL_TAG_NONE - 1)
#define OBJ_EVENT_PAL_TAG_NONE                    0xFFFF

// This + localId is used as the tileTag
// for compressed graphicsInfos
// '(C)ompressed (E)vent'
#define COMP_OW_TILE_TAG_BASE 0xCE00

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
