gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "And this… {PAUSE 96}\nis what we call a “Pokémon.”\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\ncreatures known as Pokémon.\pWe humans live alongside Pokémon, at\ntimes playing together as friends,\land at times helping one another.\pAnd sometimes, we just like to have\nfun battling others like us!\pBut as close as we are, we don't\nknow everything about Pokémon.\pIn fact, there are still many, many\nmysteries surrounding Pokémon.\pI do research to try to unravel\nthose mysteries.\pBut that's enough about me!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What about you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Will you give me your name, too?$"

gText_Birch_SoItsPlayer::
	.string "So you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah… I see!\nYou're THAT {PLAYER}!\pYou're the one who's moving to\nLittleroot Town, where I live!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\pYour very own adventure is now about\nto unfold!\pBe courageous and leap in to the\nworld of Pokémon where dreams,\ladventures, and friendships await!\pI expect we'll be meeting again\nsoon.\pCome see me in my Pokémon Lab!\p"
	.string "$"
