gText_ObtainedTheItem::
	.string "{PLAYER} obtained\n{COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_ObtainedTheItems::
    .string "{PLAYER} obtained\n{STR_VAR_1} {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TheBagIsFull::
	.string "The Bag is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put the {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}\n"
	.string "in the {COLOR BLUE}{STR_VAR_3} Pocket{COLOR DARK_GRAY}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_PlayerFoundItems::
    .string "{PLAYER} found {STR_VAR_1} {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The Bag is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put the {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}\n"
	.string "in the {COLOR BLUE}Bag{COLOR DARK_GRAY}.$"

gText_ObtainedTheDecor::
	.string "{PLAYER} obtained\n{COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY} was transferred\n"
	.string "to the PC.$"
