# 1 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 2 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_MapScripts::
# 3 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.byte 0
# 4 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 5 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_EventScript_Grunt6::
# 6 "data/maps/SeafloorCavern_Room3/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_6, SeafloorCavern_Room3_Text_Grunt6Intro, SeafloorCavern_Room3_Text_Grunt6Defeat
# 7 "data/maps/SeafloorCavern_Room3/scripts.pory"
	msgbox SeafloorCavern_Room3_Text_Grunt6PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SeafloorCavern_Room3/scripts.pory"
	end
# 9 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 10 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_EventScript_Grunt5::
# 11 "data/maps/SeafloorCavern_Room3/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_5, SeafloorCavern_Room3_Text_Grunt5Intro, SeafloorCavern_Room3_Text_Grunt5Defeat
# 12 "data/maps/SeafloorCavern_Room3/scripts.pory"
	msgbox SeafloorCavern_Room3_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SeafloorCavern_Room3/scripts.pory"
	end
# 14 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 15 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt6Intro:
# 16 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\pHow did you manage to get here\nwithout a submarine?\pWhat an impressive child!\pBut… It won't do to have you meddling\nabout here.\pI'm going to give you a little taste\nof pain! Resign yourself to it!$"
# 17 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 18 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt6Defeat:
# 19 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\pOuch!$"
# 20 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 21 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt6PostBattle:
# 22 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\nYou're so darn strong.\pIt's terribly disappointing that you're\nnot a Team Aqua member.\pYou could have enjoyed the fabulous\nworld our Boss has promised as one of\lus…$"
# 23 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 24 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5Intro:
# 25 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "For our dream to become real, we need\nthe power of Pokémon.\pBut meddlers like you use the power\nof Pokémon to mess with us even at a\lplace like this!\pLife just doesn't work the way we need\nit to!$"
# 26 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 27 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5Defeat:
# 28 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Gwah!$"
# 29 "data/maps/SeafloorCavern_Room3/scripts.pory"

# 30 "data/maps/SeafloorCavern_Room3/scripts.pory"
SeafloorCavern_Room3_Text_Grunt5PostBattle:
# 31 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "You know, we don't dare question the\nmotives of our leader.\pBut here you are, just some punk,\ngoing up against our Boss.\pMaybe…\nYou must be something…$"
