PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Our city's new Gym Leader is a man\ncalled Norman.\pI heard he moved his whole family\nhere from the Johto region.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I battled Norman once, but he was\nway too strong!\pWhew! How should I put it…\pI just really got the feeling that\nhe lives for Pokémon.$"

