# 1 "data/maps/SlateportCity_House/scripts.pory"

# 2 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_MapScripts::
# 3 "data/maps/SlateportCity_House/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House/scripts.pory"

# 5 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_PokefanM::
# 6 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House/scripts.pory"

# 9 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_Girl::
# 10 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
# 11 "data/maps/SlateportCity_House/scripts.pory"
	end
# 12 "data/maps/SlateportCity_House/scripts.pory"

# 13 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_NatureToDoWithStatGains:
# 14 "data/maps/SlateportCity_House/scripts.pory"
	.string "My Pokémon has a Hasty Nature.\nAnd it has a higher Speed stat than\lmy other Pokémon.\pMaybe nature has something to do with\nhow the stats grow?$"
# 15 "data/maps/SlateportCity_House/scripts.pory"

# 16 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_MustBeGoingToBattleTent:
# 17 "data/maps/SlateportCity_House/scripts.pory"
	.string "You'll need a Contest Pass if you want\nto enter a contest.\pI got mine from the famous contest\nstar Lisia!$"
