PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Ah, a journey is a wonderful thing!\pWhen I was young, I also roamed\nacross the seas and the mountains!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sigh…\pI wish I could go on an adventure\nwith Pokémon…\pCrawl though some damp grass…\nClimb rocky, rugged mountains…\pCross the raging seas…\nWander about in dark caves…\pAnd sometimes get a little\nhomesick…\pIt must fabulous to travel!$"

