PetalburgWoods_2_MapScripts::
	.byte 0


PetalburgWoods_2_EventScript_Sign::
# 4 "data/maps/PetalburgWoods_2/scripts.pory"
	msgbox PetalburgWoods_2_EventScript_Sign_Text_0
# 5 "data/maps/PetalburgWoods_2/scripts.pory"
	release
	end


PetalburgWoods_2_EventScript_Sign_Text_0:
# 4 "data/maps/PetalburgWoods_2/scripts.pory"
	.string "A chilling pocket in Petalburg Woods,\nwhere an eerie cold bites through\lthe air without explanation…$"
