# 1 "data/maps/FortreeCity_House3/scripts.pory"

# 2 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_MapScripts::
# 3 "data/maps/FortreeCity_House3/scripts.pory"
	.byte 0
# 4 "data/maps/FortreeCity_House3/scripts.pory"

# 5 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_EventScript_Maniac::
# 6 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
# 7 "data/maps/FortreeCity_House3/scripts.pory"
	end
# 8 "data/maps/FortreeCity_House3/scripts.pory"

# 9 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_EventScript_SchoolKidM::
# 10 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
# 11 "data/maps/FortreeCity_House3/scripts.pory"
	end
# 12 "data/maps/FortreeCity_House3/scripts.pory"

# 13 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
# 14 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Hmm! Seeing your Pokédex just reminded\nme of something…\pI met this Trainer, Steven, when I was\nsearching for rare stones.\pHoo boy, he had some amazing Pokémon\nwith him!\pThey weren't just rare, they were\ntrained to terrifying extremes!\pHe might even be stronger that the\nGym Leader in this town…$"
# 15 "data/maps/FortreeCity_House3/scripts.pory"

# 16 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_Text_OhYouHavePokedex:
# 17 "data/maps/FortreeCity_House3/scripts.pory"
	.string "What's that thing you have there?\p…\pOh, it's called a Pokédex?\nIt's really awesome!$"
