FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Hmm! Seeing your Pokédex just reminded\nme of something…\pI met this Trainer, Steven, when I was\nsearching for rare stones.\pHoo boy, he had some amazing Pokémon\nwith him!\pThey weren't just rare, they were\ntrained to terrifying extremes!\pHe might even be stronger that the\nGym Leader in this town…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "What's that thing you have there?\p…\pOh, it's called a Pokédex?\nIt's really awesome!$"
