# 1 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 2 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_MapScripts::
# 3 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 5 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
# 6 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
# 7 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	end
# 8 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 9 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
# 10 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
# 11 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	end
# 12 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 13 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
# 14 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Making a large ship is more\nlike constructing a building than\lassembling a vehicle.$"
# 15 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 16 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
# 17 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Don't you think it's strange that\n"
# 18 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "a ship made of heavy iron floats?\p"
# 19 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "It floats because of a principle\n"
# 20 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "called buoyancy.$"
